INSERT INTO auctions_category (cat) VALUES ('Accessories');
INSERT INTO auctions_category (cat) VALUES ('Arts and Crafts');
INSERT INTO auctions_category (cat) VALUES ('Sports');
INSERT INTO auctions_category (cat) VALUES ('Fitness');
INSERT INTO auctions_category (cat) VALUES ('Furniture');
INSERT INTO auctions_category (cat) VALUES ('Health');
INSERT INTO auctions_category (cat) VALUES ('Pets');
INSERT INTO auctions_category (cat) VALUES ('Entertainment');
INSERT INTO auctions_category (cat) VALUES ('Video Games');
INSERT INTO auctions_category (cat) VALUES ('Shoes');
INSERT INTO auctions_category (cat) VALUES ('Clothing');
INSERT INTO auctions_category (cat) VALUES ('Cars');
INSERT INTO auctions_category (cat) VALUES ('Other');